from moviepy.editor import *
topRight1=VideoFileClip('/content/video/challenge_video.mp4')
topRight2=VideoFileClip('/content/video/harder_challenge_video.mp4')
topRight=clips_array([[topRight1],[topRight2]])
topLeft=VideoFileClip('/content/video/project_video.mp4')
top=clips_array([[topLeft.set_position(400,400),topRight.set_position(200,400)]])
buttomLeft=VideoFileClip('/content/video/project_video.mp4')
buttomRight=VideoFileClip('/content/video/project_video.mp4')
buttomMiddle=VideoFileClip('/content/video/harder_challenge_video.mp4')
buttom1=clips_array([[buttomLeft,buttomMiddle]])
buttom=clips_array([[buttom1.set_position(200,200),buttomRight.set_position(200,200)]])
#final_clip=clips_array([[top],[buttom]])
top.ipython_display(width=600)
top.write_videofile('/content/output/part1.mp4')
buttom.ipython_display(width=600)
buttom.write_videofile('/content/output/part2.mp4')